# Generated by Django 4.2.1 on 2023-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(blank=True, choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='like', max_length=10, null=True),
        ),
    ]
