# Generated by Django 4.2.1 on 2023-06-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_comment_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
