# Generated by Django 4.2.1 on 2023-06-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.project'),
        ),
    ]
